version: '3.8'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: pfkp-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: pfkp-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "StartProcess:1:1,FinishProcess:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - ./docker-local-data/var/run/docker.sock:/var/run/docker.sock
      - ./docker-local-data/kafka/data:/var/lib/kafka/data

  postgresql:
    image: postgres:13.0-alpine
    container_name: pfkp-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    volumes:
      - ./docker-local-data/postgresql:/var/lib/postgresql/data
    restart: always
